### ISSUE TITLE
Benign datasets missing

### ISSUE THREAD

**Issue by secDre4mer** [OTRF/Security-Datasets#48]
Hi,

The title page mentions that the project contributes malicious and benign datasets. However, all datasets in the datasets/ folder appear to be malicious. Are any benign datasets included and am I just missing them? Otherwise the title page should perhaps be updated.

**Comment by Cyb3rWard0g** [comment]
Hello @secDre4mer ! I meant that each dataset has both events generated by the adversary tradecraft simulated and others that are simply generated by the endpoint itself (normal/benign activity).

**Comment by irenebosque** [comment]
I had the same thought as @secDre4mer , I hoped the logs were labeled in the sense I could use them in supervised learning, for example. The description of that part is perhaps a bit misleading
